# Generated by Django 4.1 on 2023-05-25 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_energybill_energy_bill_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energybill',
            name='energy_bill_file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'xlsx', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
