# Generated by Django 4.1 on 2023-11-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_energybill_anotacoes'),
        ('contracts', '0012_energybill_address'),
    ]

    operations = [
    ]
